---
- name: Install Ansible Galaxy roles
  hosts: localhost
  tasks:
    - name: Install Ansible Galaxy roles
      ansible.builtin.command: ansible-galaxy install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      delegate_to: localhost

- name: Users
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: create_user
      vars:
        user: "connor"
        github_user: "Makeshift"

- name: Common
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    - user: connor
  roles:
    - role: packages
    - role: liquidprompt
    - role: neofetch
    - role: known_hosts

- name: Chezmoi
  hosts: all
  become: yes
  become_user: connor
  gather_facts: yes
  roles:
    - role: chezmoi
      vars:
        github_user: "Makeshift"
